// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module score_matrix_score_matrix_Pipeline_LOOP2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        score_m_0_address0,
        score_m_0_ce0,
        score_m_0_we0,
        score_m_0_d0,
        keys_t_0_address0,
        keys_t_0_ce0,
        keys_t_0_q0,
        empty_4,
        keys_t_1_address0,
        keys_t_1_ce0,
        keys_t_1_q0,
        empty_5,
        keys_t_2_address0,
        keys_t_2_ce0,
        keys_t_2_q0,
        empty,
        m,
        score_m_1_address0,
        score_m_1_ce0,
        score_m_1_we0,
        score_m_1_d0,
        score_m_2_address0,
        score_m_2_ce0,
        score_m_2_we0,
        score_m_2_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] score_m_0_address0;
output   score_m_0_ce0;
output   score_m_0_we0;
output  [31:0] score_m_0_d0;
output  [1:0] keys_t_0_address0;
output   keys_t_0_ce0;
input  [31:0] keys_t_0_q0;
input  [31:0] empty_4;
output  [1:0] keys_t_1_address0;
output   keys_t_1_ce0;
input  [31:0] keys_t_1_q0;
input  [31:0] empty_5;
output  [1:0] keys_t_2_address0;
output   keys_t_2_ce0;
input  [31:0] keys_t_2_q0;
input  [31:0] empty;
input  [1:0] m;
output  [1:0] score_m_1_address0;
output   score_m_1_ce0;
output   score_m_1_we0;
output  [31:0] score_m_1_d0;
output  [1:0] score_m_2_address0;
output   score_m_2_ce0;
output   score_m_2_we0;
output  [31:0] score_m_2_d0;

reg ap_idle;
reg score_m_0_ce0;
reg score_m_0_we0;
reg keys_t_0_ce0;
reg keys_t_1_ce0;
reg keys_t_2_ce0;
reg score_m_1_ce0;
reg score_m_1_we0;
reg score_m_2_ce0;
reg score_m_2_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln12_fu_195_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] m_read_reg_251;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln12_fu_207_p1;
reg   [63:0] zext_ln12_reg_274;
reg   [63:0] zext_ln12_reg_274_pp0_iter1_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter2_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter3_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter4_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter5_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter6_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter7_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter8_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter9_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter10_reg;
reg   [63:0] zext_ln12_reg_274_pp0_iter11_reg;
wire   [31:0] grp_fu_175_p2;
reg   [31:0] mul_reg_293;
wire   [31:0] grp_fu_162_p2;
reg   [31:0] add_reg_308;
wire   [31:0] grp_fu_179_p2;
reg   [31:0] mul_1_reg_313;
wire   [31:0] grp_fu_167_p2;
reg   [31:0] add_1_reg_328;
wire   [31:0] grp_fu_183_p2;
reg   [31:0] mul_2_reg_333;
wire   [31:0] grp_fu_171_p2;
reg   [31:0] add_2_reg_338;
wire    ap_block_pp0_stage0;
reg   [1:0] o_fu_56;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_o_1;
wire   [1:0] add_ln12_fu_201_p2;
wire   [31:0] grp_fu_175_p1;
wire   [31:0] grp_fu_179_p1;
wire   [31:0] grp_fu_183_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_293),
    .din1(32'd0),
    .ce(1'b1),
    .dout(grp_fu_162_p2)
);

score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_reg_308),
    .din1(mul_1_reg_313),
    .ce(1'b1),
    .dout(grp_fu_167_p2)
);

score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_1_reg_328),
    .din1(mul_2_reg_333),
    .ce(1'b1),
    .dout(grp_fu_171_p2)
);

score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_4),
    .din1(grp_fu_175_p1),
    .ce(1'b1),
    .dout(grp_fu_175_p2)
);

score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_5),
    .din1(grp_fu_179_p1),
    .ce(1'b1),
    .dout(grp_fu_179_p2)
);

score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty),
    .din1(grp_fu_183_p1),
    .ce(1'b1),
    .dout(grp_fu_183_p2)
);

score_matrix_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln12_fu_195_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            o_fu_56 <= add_ln12_fu_201_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_56 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_1_reg_328 <= grp_fu_167_p2;
        add_2_reg_338 <= grp_fu_171_p2;
        add_reg_308 <= grp_fu_162_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        mul_1_reg_313 <= grp_fu_179_p2;
        mul_2_reg_333 <= grp_fu_183_p2;
        mul_reg_293 <= grp_fu_175_p2;
        zext_ln12_reg_274_pp0_iter10_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter9_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter11_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter10_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter2_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter1_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter3_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter2_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter4_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter3_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter5_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter4_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter6_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter5_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter7_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter6_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter8_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter7_reg[1 : 0];
        zext_ln12_reg_274_pp0_iter9_reg[1 : 0] <= zext_ln12_reg_274_pp0_iter8_reg[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        zext_ln12_reg_274_pp0_iter1_reg[1 : 0] <= zext_ln12_reg_274[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln12_fu_195_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln12_reg_274[1 : 0] <= zext_ln12_fu_207_p1[1 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln12_fu_195_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_o_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_o_1 = o_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        keys_t_0_ce0 = 1'b1;
    end else begin
        keys_t_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        keys_t_1_ce0 = 1'b1;
    end else begin
        keys_t_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        keys_t_2_ce0 = 1'b1;
    end else begin
        keys_t_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_0_ce0 = 1'b1;
    end else begin
        score_m_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (m_read_reg_251 == 2'd0))) begin
        score_m_0_we0 = 1'b1;
    end else begin
        score_m_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_1_ce0 = 1'b1;
    end else begin
        score_m_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (m_read_reg_251 == 2'd1))) begin
        score_m_1_we0 = 1'b1;
    end else begin
        score_m_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_2_ce0 = 1'b1;
    end else begin
        score_m_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(m_read_reg_251 == 2'd0) & ~(m_read_reg_251 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_2_we0 = 1'b1;
    end else begin
        score_m_2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_fu_201_p2 = (ap_sig_allocacmp_o_1 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_175_p1 = keys_t_0_q0;

assign grp_fu_179_p1 = keys_t_1_q0;

assign grp_fu_183_p1 = keys_t_2_q0;

assign icmp_ln12_fu_195_p2 = ((ap_sig_allocacmp_o_1 == 2'd3) ? 1'b1 : 1'b0);

assign keys_t_0_address0 = zext_ln12_fu_207_p1;

assign keys_t_1_address0 = zext_ln12_reg_274_pp0_iter2_reg;

assign keys_t_2_address0 = zext_ln12_reg_274_pp0_iter5_reg;

assign m_read_reg_251 = m;

assign score_m_0_address0 = zext_ln12_reg_274_pp0_iter11_reg;

assign score_m_0_d0 = add_2_reg_338;

assign score_m_1_address0 = zext_ln12_reg_274_pp0_iter11_reg;

assign score_m_1_d0 = add_2_reg_338;

assign score_m_2_address0 = zext_ln12_reg_274_pp0_iter11_reg;

assign score_m_2_d0 = add_2_reg_338;

assign zext_ln12_fu_207_p1 = ap_sig_allocacmp_o_1;

always @ (posedge ap_clk) begin
    zext_ln12_reg_274[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter1_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter2_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter3_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter4_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter5_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter6_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter7_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter8_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter9_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter10_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    zext_ln12_reg_274_pp0_iter11_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //score_matrix_score_matrix_Pipeline_LOOP2
