// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module score_matrix_score_matrix_Pipeline_LOOP1_LOOP2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        queries_0_load,
        queries_2_load,
        queries_1_load,
        queries_0_load_1,
        queries_2_load_1,
        queries_1_load_1,
        queries_0_load_2,
        queries_2_load_2,
        queries_1_load_2,
        score_m_0_address0,
        score_m_0_ce0,
        score_m_0_we0,
        score_m_0_d0,
        score_m_0_address1,
        score_m_0_ce1,
        score_m_0_we1,
        score_m_0_d1,
        keys_t_2_address0,
        keys_t_2_ce0,
        keys_t_2_q0,
        keys_t_0_address0,
        keys_t_0_ce0,
        keys_t_0_q0,
        keys_t_1_address0,
        keys_t_1_ce0,
        keys_t_1_q0,
        score_m_1_address0,
        score_m_1_ce0,
        score_m_1_we0,
        score_m_1_d0,
        score_m_1_address1,
        score_m_1_ce1,
        score_m_1_we1,
        score_m_1_d1,
        score_m_2_address0,
        score_m_2_ce0,
        score_m_2_we0,
        score_m_2_d0,
        score_m_2_address1,
        score_m_2_ce1,
        score_m_2_we1,
        score_m_2_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] queries_0_load;
input  [31:0] queries_2_load;
input  [31:0] queries_1_load;
input  [31:0] queries_0_load_1;
input  [31:0] queries_2_load_1;
input  [31:0] queries_1_load_1;
input  [31:0] queries_0_load_2;
input  [31:0] queries_2_load_2;
input  [31:0] queries_1_load_2;
output  [1:0] score_m_0_address0;
output   score_m_0_ce0;
output   score_m_0_we0;
output  [31:0] score_m_0_d0;
output  [1:0] score_m_0_address1;
output   score_m_0_ce1;
output   score_m_0_we1;
output  [31:0] score_m_0_d1;
output  [1:0] keys_t_2_address0;
output   keys_t_2_ce0;
input  [31:0] keys_t_2_q0;
output  [1:0] keys_t_0_address0;
output   keys_t_0_ce0;
input  [31:0] keys_t_0_q0;
output  [1:0] keys_t_1_address0;
output   keys_t_1_ce0;
input  [31:0] keys_t_1_q0;
output  [1:0] score_m_1_address0;
output   score_m_1_ce0;
output   score_m_1_we0;
output  [31:0] score_m_1_d0;
output  [1:0] score_m_1_address1;
output   score_m_1_ce1;
output   score_m_1_we1;
output  [31:0] score_m_1_d1;
output  [1:0] score_m_2_address0;
output   score_m_2_ce0;
output   score_m_2_we0;
output  [31:0] score_m_2_d0;
output  [1:0] score_m_2_address1;
output   score_m_2_ce1;
output   score_m_2_we1;
output  [31:0] score_m_2_d1;

reg ap_idle;
reg score_m_0_ce0;
reg score_m_0_we0;
reg score_m_0_ce1;
reg score_m_0_we1;
reg keys_t_2_ce0;
reg keys_t_0_ce0;
reg keys_t_1_ce0;
reg score_m_1_ce0;
reg score_m_1_we0;
reg score_m_1_ce1;
reg score_m_1_we1;
reg score_m_2_ce0;
reg score_m_2_we0;
reg score_m_2_ce1;
reg score_m_2_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    ap_block_state9_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln11_fu_303_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] m_1_reg_595;
reg   [0:0] icmp_ln11_reg_601;
reg   [0:0] icmp_ln11_reg_601_pp0_iter1_reg;
reg   [0:0] icmp_ln11_reg_601_pp0_iter2_reg;
reg   [0:0] icmp_ln11_reg_601_pp0_iter3_reg;
reg   [0:0] icmp_ln11_reg_601_pp0_iter4_reg;
reg   [0:0] icmp_ln11_reg_601_pp0_iter5_reg;
reg   [0:0] icmp_ln11_reg_601_pp0_iter6_reg;
wire   [0:0] icmp_ln12_fu_318_p2;
reg   [0:0] icmp_ln12_reg_605;
reg   [0:0] icmp_ln12_reg_605_pp0_iter1_reg;
reg   [0:0] icmp_ln12_reg_605_pp0_iter2_reg;
reg   [0:0] icmp_ln12_reg_605_pp0_iter3_reg;
reg   [0:0] icmp_ln12_reg_605_pp0_iter4_reg;
reg   [0:0] icmp_ln12_reg_605_pp0_iter5_reg;
reg   [0:0] icmp_ln12_reg_605_pp0_iter6_reg;
wire   [0:0] icmp_ln19_2_fu_338_p2;
reg   [0:0] icmp_ln19_2_reg_612;
reg   [0:0] icmp_ln19_2_reg_612_pp0_iter1_reg;
reg   [0:0] icmp_ln19_2_reg_612_pp0_iter2_reg;
reg   [0:0] icmp_ln19_2_reg_612_pp0_iter3_reg;
reg   [0:0] icmp_ln19_2_reg_612_pp0_iter4_reg;
reg   [0:0] icmp_ln19_2_reg_612_pp0_iter5_reg;
reg   [0:0] icmp_ln19_2_reg_612_pp0_iter6_reg;
wire   [1:0] select_ln11_4_fu_344_p3;
reg   [1:0] select_ln11_4_reg_619;
reg   [1:0] select_ln11_4_reg_619_pp0_iter1_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter2_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter3_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter4_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter5_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter6_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter7_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter8_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter9_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter10_reg;
reg   [1:0] select_ln11_4_reg_619_pp0_iter11_reg;
wire   [63:0] o_cast_fu_352_p1;
reg   [63:0] o_cast_reg_623;
reg   [63:0] o_cast_reg_623_pp0_iter1_reg;
reg   [63:0] o_cast_reg_623_pp0_iter2_reg;
reg   [63:0] o_cast_reg_623_pp0_iter3_reg;
reg   [63:0] o_cast_reg_623_pp0_iter4_reg;
reg   [63:0] o_cast_reg_623_pp0_iter5_reg;
reg   [63:0] o_cast_reg_623_pp0_iter6_reg;
reg   [63:0] o_cast_reg_623_pp0_iter7_reg;
reg   [63:0] o_cast_reg_623_pp0_iter8_reg;
reg   [63:0] o_cast_reg_623_pp0_iter9_reg;
reg   [63:0] o_cast_reg_623_pp0_iter10_reg;
reg   [63:0] o_cast_reg_623_pp0_iter11_reg;
wire   [0:0] icmp_ln19_fu_378_p2;
reg   [0:0] icmp_ln19_reg_640;
reg   [0:0] icmp_ln19_reg_640_pp0_iter2_reg;
reg   [0:0] icmp_ln19_reg_640_pp0_iter3_reg;
reg   [0:0] icmp_ln19_reg_640_pp0_iter4_reg;
reg   [0:0] icmp_ln19_reg_640_pp0_iter5_reg;
reg   [0:0] icmp_ln19_reg_640_pp0_iter6_reg;
wire   [0:0] icmp_ln19_1_fu_389_p2;
reg   [0:0] icmp_ln19_1_reg_648;
reg   [0:0] icmp_ln19_1_reg_648_pp0_iter2_reg;
reg   [0:0] icmp_ln19_1_reg_648_pp0_iter3_reg;
reg   [0:0] icmp_ln19_1_reg_648_pp0_iter4_reg;
reg   [0:0] icmp_ln19_1_reg_648_pp0_iter5_reg;
reg   [0:0] icmp_ln19_1_reg_648_pp0_iter6_reg;
wire   [31:0] grp_fu_270_p2;
reg   [31:0] mul_reg_664;
wire   [31:0] grp_fu_257_p2;
reg   [31:0] add_reg_684;
wire   [31:0] grp_fu_274_p2;
reg   [31:0] mul_1_reg_689;
wire   [31:0] grp_fu_262_p2;
reg   [31:0] add_1_reg_709;
wire   [31:0] grp_fu_278_p2;
reg   [31:0] mul_2_reg_714;
wire   [31:0] grp_fu_266_p2;
reg   [31:0] add_2_reg_719;
reg    ap_condition_exit_pp0_iter7_stage0;
wire    ap_block_pp0_stage0;
reg   [1:0] o_fu_74;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_o_load;
wire   [1:0] add_ln12_fu_357_p2;
reg   [1:0] m_fu_78;
reg   [1:0] ap_sig_allocacmp_m_1;
reg   [3:0] indvar_flatten_fu_82;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [3:0] add_ln11_fu_309_p2;
wire   [31:0] grp_fu_270_p0;
wire   [31:0] grp_fu_270_p1;
wire   [31:0] grp_fu_274_p0;
wire   [31:0] grp_fu_274_p1;
wire   [31:0] grp_fu_278_p0;
wire   [31:0] grp_fu_278_p1;
wire   [1:0] add_ln11_1_fu_332_p2;
wire   [1:0] select_ln11_fu_324_p3;
wire   [31:0] select_ln19_fu_383_p3;
wire   [31:0] select_ln19_3_fu_401_p3;
wire   [31:0] p_in_0_mid1_fu_406_p3;
wire   [31:0] p_in_0_fu_394_p3;
wire   [31:0] select_ln11_1_fu_413_p3;
wire   [31:0] select_ln19_1_fu_430_p3;
wire   [31:0] select_ln19_4_fu_441_p3;
wire   [31:0] p_in_1_mid1_fu_446_p3;
wire   [31:0] p_in_1_fu_435_p3;
wire   [31:0] select_ln11_2_fu_452_p3;
wire   [31:0] select_ln19_2_fu_469_p3;
wire   [31:0] select_ln19_5_fu_480_p3;
wire   [31:0] p_in_2_mid1_fu_485_p3;
wire   [31:0] p_in_2_fu_474_p3;
wire   [31:0] select_ln11_3_fu_491_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_664),
    .din1(32'd0),
    .ce(1'b1),
    .dout(grp_fu_257_p2)
);

score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_reg_684),
    .din1(mul_1_reg_689),
    .ce(1'b1),
    .dout(grp_fu_262_p2)
);

score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_3_full_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_1_reg_709),
    .din1(mul_2_reg_714),
    .ce(1'b1),
    .dout(grp_fu_266_p2)
);

score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_270_p0),
    .din1(grp_fu_270_p1),
    .ce(1'b1),
    .dout(grp_fu_270_p2)
);

score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_274_p0),
    .din1(grp_fu_274_p1),
    .ce(1'b1),
    .dout(grp_fu_274_p2)
);

score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_278_p0),
    .din1(grp_fu_278_p1),
    .ce(1'b1),
    .dout(grp_fu_278_p2)
);

score_matrix_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter7_stage0)) begin
            ap_enable_reg_pp0_iter8 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln11_fu_303_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln11_fu_309_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln11_fu_303_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            m_fu_78 <= select_ln11_4_fu_344_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            m_fu_78 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln11_fu_303_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            o_fu_74 <= add_ln12_fu_357_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_74 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_1_reg_709 <= grp_fu_262_p2;
        add_2_reg_719 <= grp_fu_266_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln11_reg_601_pp0_iter2_reg <= icmp_ln11_reg_601_pp0_iter1_reg;
        icmp_ln11_reg_601_pp0_iter3_reg <= icmp_ln11_reg_601_pp0_iter2_reg;
        icmp_ln11_reg_601_pp0_iter4_reg <= icmp_ln11_reg_601_pp0_iter3_reg;
        icmp_ln11_reg_601_pp0_iter5_reg <= icmp_ln11_reg_601_pp0_iter4_reg;
        icmp_ln11_reg_601_pp0_iter6_reg <= icmp_ln11_reg_601_pp0_iter5_reg;
        icmp_ln12_reg_605_pp0_iter2_reg <= icmp_ln12_reg_605_pp0_iter1_reg;
        icmp_ln12_reg_605_pp0_iter3_reg <= icmp_ln12_reg_605_pp0_iter2_reg;
        icmp_ln12_reg_605_pp0_iter4_reg <= icmp_ln12_reg_605_pp0_iter3_reg;
        icmp_ln12_reg_605_pp0_iter5_reg <= icmp_ln12_reg_605_pp0_iter4_reg;
        icmp_ln12_reg_605_pp0_iter6_reg <= icmp_ln12_reg_605_pp0_iter5_reg;
        icmp_ln19_1_reg_648_pp0_iter2_reg <= icmp_ln19_1_reg_648;
        icmp_ln19_1_reg_648_pp0_iter3_reg <= icmp_ln19_1_reg_648_pp0_iter2_reg;
        icmp_ln19_1_reg_648_pp0_iter4_reg <= icmp_ln19_1_reg_648_pp0_iter3_reg;
        icmp_ln19_1_reg_648_pp0_iter5_reg <= icmp_ln19_1_reg_648_pp0_iter4_reg;
        icmp_ln19_1_reg_648_pp0_iter6_reg <= icmp_ln19_1_reg_648_pp0_iter5_reg;
        icmp_ln19_2_reg_612_pp0_iter2_reg <= icmp_ln19_2_reg_612_pp0_iter1_reg;
        icmp_ln19_2_reg_612_pp0_iter3_reg <= icmp_ln19_2_reg_612_pp0_iter2_reg;
        icmp_ln19_2_reg_612_pp0_iter4_reg <= icmp_ln19_2_reg_612_pp0_iter3_reg;
        icmp_ln19_2_reg_612_pp0_iter5_reg <= icmp_ln19_2_reg_612_pp0_iter4_reg;
        icmp_ln19_2_reg_612_pp0_iter6_reg <= icmp_ln19_2_reg_612_pp0_iter5_reg;
        icmp_ln19_reg_640_pp0_iter2_reg <= icmp_ln19_reg_640;
        icmp_ln19_reg_640_pp0_iter3_reg <= icmp_ln19_reg_640_pp0_iter2_reg;
        icmp_ln19_reg_640_pp0_iter4_reg <= icmp_ln19_reg_640_pp0_iter3_reg;
        icmp_ln19_reg_640_pp0_iter5_reg <= icmp_ln19_reg_640_pp0_iter4_reg;
        icmp_ln19_reg_640_pp0_iter6_reg <= icmp_ln19_reg_640_pp0_iter5_reg;
        mul_2_reg_714 <= grp_fu_278_p2;
        o_cast_reg_623_pp0_iter10_reg[1 : 0] <= o_cast_reg_623_pp0_iter9_reg[1 : 0];
        o_cast_reg_623_pp0_iter11_reg[1 : 0] <= o_cast_reg_623_pp0_iter10_reg[1 : 0];
        o_cast_reg_623_pp0_iter2_reg[1 : 0] <= o_cast_reg_623_pp0_iter1_reg[1 : 0];
        o_cast_reg_623_pp0_iter3_reg[1 : 0] <= o_cast_reg_623_pp0_iter2_reg[1 : 0];
        o_cast_reg_623_pp0_iter4_reg[1 : 0] <= o_cast_reg_623_pp0_iter3_reg[1 : 0];
        o_cast_reg_623_pp0_iter5_reg[1 : 0] <= o_cast_reg_623_pp0_iter4_reg[1 : 0];
        o_cast_reg_623_pp0_iter6_reg[1 : 0] <= o_cast_reg_623_pp0_iter5_reg[1 : 0];
        o_cast_reg_623_pp0_iter7_reg[1 : 0] <= o_cast_reg_623_pp0_iter6_reg[1 : 0];
        o_cast_reg_623_pp0_iter8_reg[1 : 0] <= o_cast_reg_623_pp0_iter7_reg[1 : 0];
        o_cast_reg_623_pp0_iter9_reg[1 : 0] <= o_cast_reg_623_pp0_iter8_reg[1 : 0];
        select_ln11_4_reg_619_pp0_iter10_reg <= select_ln11_4_reg_619_pp0_iter9_reg;
        select_ln11_4_reg_619_pp0_iter11_reg <= select_ln11_4_reg_619_pp0_iter10_reg;
        select_ln11_4_reg_619_pp0_iter2_reg <= select_ln11_4_reg_619_pp0_iter1_reg;
        select_ln11_4_reg_619_pp0_iter3_reg <= select_ln11_4_reg_619_pp0_iter2_reg;
        select_ln11_4_reg_619_pp0_iter4_reg <= select_ln11_4_reg_619_pp0_iter3_reg;
        select_ln11_4_reg_619_pp0_iter5_reg <= select_ln11_4_reg_619_pp0_iter4_reg;
        select_ln11_4_reg_619_pp0_iter6_reg <= select_ln11_4_reg_619_pp0_iter5_reg;
        select_ln11_4_reg_619_pp0_iter7_reg <= select_ln11_4_reg_619_pp0_iter6_reg;
        select_ln11_4_reg_619_pp0_iter8_reg <= select_ln11_4_reg_619_pp0_iter7_reg;
        select_ln11_4_reg_619_pp0_iter9_reg <= select_ln11_4_reg_619_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln11_reg_601_pp0_iter4_reg == 1'd0))) begin
        add_reg_684 <= grp_fu_257_p2;
        mul_1_reg_689 <= grp_fu_274_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln11_reg_601 <= icmp_ln11_fu_303_p2;
        icmp_ln11_reg_601_pp0_iter1_reg <= icmp_ln11_reg_601;
        icmp_ln12_reg_605_pp0_iter1_reg <= icmp_ln12_reg_605;
        icmp_ln19_1_reg_648 <= icmp_ln19_1_fu_389_p2;
        icmp_ln19_2_reg_612_pp0_iter1_reg <= icmp_ln19_2_reg_612;
        icmp_ln19_reg_640 <= icmp_ln19_fu_378_p2;
        m_1_reg_595 <= ap_sig_allocacmp_m_1;
        o_cast_reg_623_pp0_iter1_reg[1 : 0] <= o_cast_reg_623[1 : 0];
        select_ln11_4_reg_619_pp0_iter1_reg <= select_ln11_4_reg_619;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln11_fu_303_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln12_reg_605 <= icmp_ln12_fu_318_p2;
        icmp_ln19_2_reg_612 <= icmp_ln19_2_fu_338_p2;
        o_cast_reg_623[1 : 0] <= o_cast_fu_352_p1[1 : 0];
        select_ln11_4_reg_619 <= select_ln11_4_fu_344_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln11_reg_601_pp0_iter1_reg == 1'd0))) begin
        mul_reg_664 <= grp_fu_270_p2;
    end
end

always @ (*) begin
    if (((icmp_ln11_fu_303_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln11_reg_601_pp0_iter6_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter7_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter7_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_m_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_m_1 = m_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_o_load = 2'd0;
    end else begin
        ap_sig_allocacmp_o_load = o_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        keys_t_0_ce0 = 1'b1;
    end else begin
        keys_t_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        keys_t_1_ce0 = 1'b1;
    end else begin
        keys_t_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        keys_t_2_ce0 = 1'b1;
    end else begin
        keys_t_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_0_ce0 = 1'b1;
    end else begin
        score_m_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        score_m_0_ce1 = 1'b1;
    end else begin
        score_m_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (select_ln11_4_reg_619_pp0_iter11_reg == 2'd0))) begin
        score_m_0_we0 = 1'b1;
    end else begin
        score_m_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_4_reg_619_pp0_iter9_reg == 2'd0))) begin
        score_m_0_we1 = 1'b1;
    end else begin
        score_m_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_1_ce0 = 1'b1;
    end else begin
        score_m_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        score_m_1_ce1 = 1'b1;
    end else begin
        score_m_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (select_ln11_4_reg_619_pp0_iter11_reg == 2'd1))) begin
        score_m_1_we0 = 1'b1;
    end else begin
        score_m_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_4_reg_619_pp0_iter9_reg == 2'd1))) begin
        score_m_1_we1 = 1'b1;
    end else begin
        score_m_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_2_ce0 = 1'b1;
    end else begin
        score_m_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        score_m_2_ce1 = 1'b1;
    end else begin
        score_m_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_4_reg_619_pp0_iter11_reg == 2'd0) & ~(select_ln11_4_reg_619_pp0_iter11_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        score_m_2_we0 = 1'b1;
    end else begin
        score_m_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_4_reg_619_pp0_iter9_reg == 2'd0) & ~(select_ln11_4_reg_619_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        score_m_2_we1 = 1'b1;
    end else begin
        score_m_2_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln11_1_fu_332_p2 = (ap_sig_allocacmp_m_1 + 2'd1);

assign add_ln11_fu_309_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln12_fu_357_p2 = (select_ln11_fu_324_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_270_p0 = select_ln11_1_fu_413_p3;

assign grp_fu_270_p1 = keys_t_0_q0;

assign grp_fu_274_p0 = select_ln11_2_fu_452_p3;

assign grp_fu_274_p1 = keys_t_1_q0;

assign grp_fu_278_p0 = select_ln11_3_fu_491_p3;

assign grp_fu_278_p1 = keys_t_2_q0;

assign icmp_ln11_fu_303_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_318_p2 = ((ap_sig_allocacmp_o_load == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln19_1_fu_389_p2 = ((m_1_reg_595 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln19_2_fu_338_p2 = ((add_ln11_1_fu_332_p2 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_378_p2 = ((m_1_reg_595 == 2'd0) ? 1'b1 : 1'b0);

assign keys_t_0_address0 = o_cast_fu_352_p1;

assign keys_t_1_address0 = o_cast_reg_623_pp0_iter2_reg;

assign keys_t_2_address0 = o_cast_reg_623_pp0_iter5_reg;

assign o_cast_fu_352_p1 = select_ln11_fu_324_p3;

assign p_in_0_fu_394_p3 = ((icmp_ln19_1_fu_389_p2[0:0] == 1'b1) ? queries_1_load : select_ln19_fu_383_p3);

assign p_in_0_mid1_fu_406_p3 = ((icmp_ln19_fu_378_p2[0:0] == 1'b1) ? queries_1_load : select_ln19_3_fu_401_p3);

assign p_in_1_fu_435_p3 = ((icmp_ln19_1_reg_648_pp0_iter3_reg[0:0] == 1'b1) ? queries_1_load_1 : select_ln19_1_fu_430_p3);

assign p_in_1_mid1_fu_446_p3 = ((icmp_ln19_reg_640_pp0_iter3_reg[0:0] == 1'b1) ? queries_1_load_1 : select_ln19_4_fu_441_p3);

assign p_in_2_fu_474_p3 = ((icmp_ln19_1_reg_648_pp0_iter6_reg[0:0] == 1'b1) ? queries_1_load_2 : select_ln19_2_fu_469_p3);

assign p_in_2_mid1_fu_485_p3 = ((icmp_ln19_reg_640_pp0_iter6_reg[0:0] == 1'b1) ? queries_1_load_2 : select_ln19_5_fu_480_p3);

assign score_m_0_address0 = o_cast_reg_623_pp0_iter11_reg;

assign score_m_0_address1 = o_cast_reg_623_pp0_iter9_reg;

assign score_m_0_d0 = add_2_reg_719;

assign score_m_0_d1 = 32'd0;

assign score_m_1_address0 = o_cast_reg_623_pp0_iter11_reg;

assign score_m_1_address1 = o_cast_reg_623_pp0_iter9_reg;

assign score_m_1_d0 = add_2_reg_719;

assign score_m_1_d1 = 32'd0;

assign score_m_2_address0 = o_cast_reg_623_pp0_iter11_reg;

assign score_m_2_address1 = o_cast_reg_623_pp0_iter9_reg;

assign score_m_2_d0 = add_2_reg_719;

assign score_m_2_d1 = 32'd0;

assign select_ln11_1_fu_413_p3 = ((icmp_ln12_reg_605[0:0] == 1'b1) ? p_in_0_mid1_fu_406_p3 : p_in_0_fu_394_p3);

assign select_ln11_2_fu_452_p3 = ((icmp_ln12_reg_605_pp0_iter3_reg[0:0] == 1'b1) ? p_in_1_mid1_fu_446_p3 : p_in_1_fu_435_p3);

assign select_ln11_3_fu_491_p3 = ((icmp_ln12_reg_605_pp0_iter6_reg[0:0] == 1'b1) ? p_in_2_mid1_fu_485_p3 : p_in_2_fu_474_p3);

assign select_ln11_4_fu_344_p3 = ((icmp_ln12_fu_318_p2[0:0] == 1'b1) ? add_ln11_1_fu_332_p2 : ap_sig_allocacmp_m_1);

assign select_ln11_fu_324_p3 = ((icmp_ln12_fu_318_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_o_load);

assign select_ln19_1_fu_430_p3 = ((icmp_ln19_reg_640_pp0_iter3_reg[0:0] == 1'b1) ? queries_0_load_1 : queries_2_load_1);

assign select_ln19_2_fu_469_p3 = ((icmp_ln19_reg_640_pp0_iter6_reg[0:0] == 1'b1) ? queries_0_load_2 : queries_2_load_2);

assign select_ln19_3_fu_401_p3 = ((icmp_ln19_2_reg_612[0:0] == 1'b1) ? queries_0_load : queries_2_load);

assign select_ln19_4_fu_441_p3 = ((icmp_ln19_2_reg_612_pp0_iter3_reg[0:0] == 1'b1) ? queries_0_load_1 : queries_2_load_1);

assign select_ln19_5_fu_480_p3 = ((icmp_ln19_2_reg_612_pp0_iter6_reg[0:0] == 1'b1) ? queries_0_load_2 : queries_2_load_2);

assign select_ln19_fu_383_p3 = ((icmp_ln19_fu_378_p2[0:0] == 1'b1) ? queries_0_load : queries_2_load);

always @ (posedge ap_clk) begin
    o_cast_reg_623[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter1_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter2_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter3_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter4_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter5_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter6_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter7_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter8_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter9_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter10_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    o_cast_reg_623_pp0_iter11_reg[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //score_matrix_score_matrix_Pipeline_LOOP1_LOOP2
