-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity score_matrix_score_matrix_Pipeline_LOOP2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    score_m_0_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    score_m_0_ce0 : OUT STD_LOGIC;
    score_m_0_we0 : OUT STD_LOGIC;
    score_m_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    keys_t_0_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_0_ce0 : OUT STD_LOGIC;
    keys_t_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_1_ce0 : OUT STD_LOGIC;
    keys_t_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_2_ce0 : OUT STD_LOGIC;
    keys_t_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_3_ce0 : OUT STD_LOGIC;
    keys_t_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_4_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_4_ce0 : OUT STD_LOGIC;
    keys_t_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_5_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_5_ce0 : OUT STD_LOGIC;
    keys_t_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_6_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_6_ce0 : OUT STD_LOGIC;
    keys_t_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_7_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    keys_t_7_ce0 : OUT STD_LOGIC;
    keys_t_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty : IN STD_LOGIC_VECTOR (31 downto 0);
    m : IN STD_LOGIC_VECTOR (1 downto 0);
    score_m_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    score_m_1_ce0 : OUT STD_LOGIC;
    score_m_1_we0 : OUT STD_LOGIC;
    score_m_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    score_m_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    score_m_2_ce0 : OUT STD_LOGIC;
    score_m_2_we0 : OUT STD_LOGIC;
    score_m_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of score_matrix_score_matrix_Pipeline_LOOP2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln14_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal m_read_reg_431 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln14_fu_362_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter16_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter17_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter18_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter19_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter20_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter21_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter22_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter23_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter24_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter25_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_reg_479_pp0_iter26_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_310_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_503 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_277_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_reg_518 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_314_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_reg_523 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_282_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_1_reg_538 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_318_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_reg_543 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_286_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_2_reg_558 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_3_reg_563 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_290_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_3_reg_578 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_326_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_4_reg_583 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_294_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_4_reg_598 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_5_reg_603 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_298_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_5_reg_618 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_6_reg_623 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_302_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_6_reg_638 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_338_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_7_reg_643 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_7_reg_648 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal o_fu_76 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_o_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln14_fu_356_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_310_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_314_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_318_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_322_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_326_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_330_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_334_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_338_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component score_matrix_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fadd_32ns_32ns_32_3_full_dsp_1_U1 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_reg_503,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        dout => grp_fu_277_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U2 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_reg_518,
        din1 => mul_1_reg_523,
        ce => ap_const_logic_1,
        dout => grp_fu_282_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U3 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_1_reg_538,
        din1 => mul_2_reg_543,
        ce => ap_const_logic_1,
        dout => grp_fu_286_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U4 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_2_reg_558,
        din1 => mul_3_reg_563,
        ce => ap_const_logic_1,
        dout => grp_fu_290_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U5 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_3_reg_578,
        din1 => mul_4_reg_583,
        ce => ap_const_logic_1,
        dout => grp_fu_294_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U6 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_4_reg_598,
        din1 => mul_5_reg_603,
        ce => ap_const_logic_1,
        dout => grp_fu_298_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U7 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_5_reg_618,
        din1 => mul_6_reg_623,
        ce => ap_const_logic_1,
        dout => grp_fu_302_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U8 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_6_reg_638,
        din1 => mul_7_reg_643,
        ce => ap_const_logic_1,
        dout => grp_fu_306_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U9 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_4,
        din1 => grp_fu_310_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_310_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U10 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_5,
        din1 => grp_fu_314_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_314_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U11 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_6,
        din1 => grp_fu_318_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_318_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U12 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_7,
        din1 => grp_fu_322_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_322_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U13 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_8,
        din1 => grp_fu_326_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_326_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U14 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_9,
        din1 => grp_fu_330_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_330_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U15 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_10,
        din1 => grp_fu_334_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_334_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U16 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty,
        din1 => grp_fu_338_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_338_p2);

    flow_control_loop_pipe_sequential_init_U : component score_matrix_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter26_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    o_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln14_fu_350_p2 = ap_const_lv1_0))) then 
                    o_fu_76 <= add_ln14_fu_356_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    o_fu_76 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_1_reg_538 <= grp_fu_282_p2;
                add_2_reg_558 <= grp_fu_286_p2;
                add_3_reg_578 <= grp_fu_290_p2;
                add_4_reg_598 <= grp_fu_294_p2;
                add_5_reg_618 <= grp_fu_298_p2;
                add_6_reg_638 <= grp_fu_302_p2;
                add_7_reg_648 <= grp_fu_306_p2;
                add_reg_518 <= grp_fu_277_p2;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                mul_1_reg_523 <= grp_fu_314_p2;
                mul_2_reg_543 <= grp_fu_318_p2;
                mul_3_reg_563 <= grp_fu_322_p2;
                mul_4_reg_583 <= grp_fu_326_p2;
                mul_5_reg_603 <= grp_fu_330_p2;
                mul_6_reg_623 <= grp_fu_334_p2;
                mul_7_reg_643 <= grp_fu_338_p2;
                mul_reg_503 <= grp_fu_310_p2;
                    zext_ln14_reg_479_pp0_iter10_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter9_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter11_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter10_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter12_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter11_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter13_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter12_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter14_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter13_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter15_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter14_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter16_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter15_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter17_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter16_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter18_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter17_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter19_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter18_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter20_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter19_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter21_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter20_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter22_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter21_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter23_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter22_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter24_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter23_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter25_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter24_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter26_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter25_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter2_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter1_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter3_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter2_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter4_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter3_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter5_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter4_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter6_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter5_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter7_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter6_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter8_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter7_reg(1 downto 0);
                    zext_ln14_reg_479_pp0_iter9_reg(1 downto 0) <= zext_ln14_reg_479_pp0_iter8_reg(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    zext_ln14_reg_479_pp0_iter1_reg(1 downto 0) <= zext_ln14_reg_479(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln14_fu_350_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    zext_ln14_reg_479(1 downto 0) <= zext_ln14_fu_362_p1(1 downto 0);
            end if;
        end if;
    end process;
    zext_ln14_reg_479(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter1_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter2_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter3_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter4_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter5_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter6_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter7_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter8_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter9_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter10_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter11_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter12_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter13_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter14_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter15_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter16_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter17_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter18_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter19_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter20_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter21_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter22_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter23_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter24_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter25_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";
    zext_ln14_reg_479_pp0_iter26_reg(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln14_fu_356_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_o_1) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln14_fu_350_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln14_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter26_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter26_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_o_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, o_fu_76, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_o_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_o_1 <= o_fu_76;
        end if; 
    end process;

    grp_fu_310_p1 <= keys_t_0_q0;
    grp_fu_314_p1 <= keys_t_1_q0;
    grp_fu_318_p1 <= keys_t_2_q0;
    grp_fu_322_p1 <= keys_t_3_q0;
    grp_fu_326_p1 <= keys_t_4_q0;
    grp_fu_330_p1 <= keys_t_5_q0;
    grp_fu_334_p1 <= keys_t_6_q0;
    grp_fu_338_p1 <= keys_t_7_q0;
    icmp_ln14_fu_350_p2 <= "1" when (ap_sig_allocacmp_o_1 = ap_const_lv2_3) else "0";
    keys_t_0_address0 <= zext_ln14_fu_362_p1(2 - 1 downto 0);

    keys_t_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_0_ce0 <= ap_const_logic_1;
        else 
            keys_t_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    keys_t_1_address0 <= zext_ln14_reg_479_pp0_iter2_reg(2 - 1 downto 0);

    keys_t_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_1_ce0 <= ap_const_logic_1;
        else 
            keys_t_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    keys_t_2_address0 <= zext_ln14_reg_479_pp0_iter5_reg(2 - 1 downto 0);

    keys_t_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_2_ce0 <= ap_const_logic_1;
        else 
            keys_t_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    keys_t_3_address0 <= zext_ln14_reg_479_pp0_iter8_reg(2 - 1 downto 0);

    keys_t_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_3_ce0 <= ap_const_logic_1;
        else 
            keys_t_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    keys_t_4_address0 <= zext_ln14_reg_479_pp0_iter11_reg(2 - 1 downto 0);

    keys_t_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_4_ce0 <= ap_const_logic_1;
        else 
            keys_t_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    keys_t_5_address0 <= zext_ln14_reg_479_pp0_iter14_reg(2 - 1 downto 0);

    keys_t_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_5_ce0 <= ap_const_logic_1;
        else 
            keys_t_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    keys_t_6_address0 <= zext_ln14_reg_479_pp0_iter17_reg(2 - 1 downto 0);

    keys_t_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter18, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_6_ce0 <= ap_const_logic_1;
        else 
            keys_t_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    keys_t_7_address0 <= zext_ln14_reg_479_pp0_iter20_reg(2 - 1 downto 0);

    keys_t_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter21, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter21 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            keys_t_7_ce0 <= ap_const_logic_1;
        else 
            keys_t_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m_read_reg_431 <= m;
    score_m_0_address0 <= zext_ln14_reg_479_pp0_iter26_reg(2 - 1 downto 0);

    score_m_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            score_m_0_ce0 <= ap_const_logic_1;
        else 
            score_m_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    score_m_0_d0 <= add_7_reg_648;

    score_m_0_we0_assign_proc : process(ap_enable_reg_pp0_iter27, m_read_reg_431, ap_block_pp0_stage0_11001)
    begin
        if (((m_read_reg_431 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            score_m_0_we0 <= ap_const_logic_1;
        else 
            score_m_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    score_m_1_address0 <= zext_ln14_reg_479_pp0_iter26_reg(2 - 1 downto 0);

    score_m_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            score_m_1_ce0 <= ap_const_logic_1;
        else 
            score_m_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    score_m_1_d0 <= add_7_reg_648;

    score_m_1_we0_assign_proc : process(ap_enable_reg_pp0_iter27, m_read_reg_431, ap_block_pp0_stage0_11001)
    begin
        if (((m_read_reg_431 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            score_m_1_we0 <= ap_const_logic_1;
        else 
            score_m_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    score_m_2_address0 <= zext_ln14_reg_479_pp0_iter26_reg(2 - 1 downto 0);

    score_m_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            score_m_2_ce0 <= ap_const_logic_1;
        else 
            score_m_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    score_m_2_d0 <= add_7_reg_648;

    score_m_2_we0_assign_proc : process(ap_enable_reg_pp0_iter27, m_read_reg_431, ap_block_pp0_stage0_11001)
    begin
        if ((not((m_read_reg_431 = ap_const_lv2_0)) and not((m_read_reg_431 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            score_m_2_we0 <= ap_const_logic_1;
        else 
            score_m_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln14_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_o_1),64));
end behav;
