-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity score_matrix is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    score_m_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    score_m_ce0 : OUT STD_LOGIC;
    score_m_we0 : OUT STD_LOGIC;
    score_m_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    queries_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    queries_ce0 : OUT STD_LOGIC;
    queries_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    queries_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    queries_ce1 : OUT STD_LOGIC;
    queries_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    keys_t_ce0 : OUT STD_LOGIC;
    keys_t_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    keys_t_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    keys_t_ce1 : OUT STD_LOGIC;
    keys_t_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of score_matrix is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "score_matrix_score_matrix,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=61,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1551,HLS_SYN_LUT=1501,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv62_3 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage3_iter1 : BOOLEAN;
    signal ap_block_state12_pp0_stage3_iter2 : BOOLEAN;
    signal ap_block_state16_pp0_stage3_iter3 : BOOLEAN;
    signal ap_block_state20_pp0_stage3_iter4 : BOOLEAN;
    signal ap_block_state24_pp0_stage3_iter5 : BOOLEAN;
    signal ap_block_state28_pp0_stage3_iter6 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal icmp_ln13_reg_713 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage3 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal grp_fu_262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_284 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_state11_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_state15_pp0_stage2_iter3 : BOOLEAN;
    signal ap_block_state19_pp0_stage2_iter4 : BOOLEAN;
    signal ap_block_state23_pp0_stage2_iter5 : BOOLEAN;
    signal ap_block_state27_pp0_stage2_iter6 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal tmp_fu_310_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_reg_705 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln13_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_reg_717 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln13_fu_349_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln13_reg_725 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_357_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_reg_732 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln13_1_fu_367_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln13_1_reg_740 : STD_LOGIC_VECTOR (1 downto 0);
    signal bitcast_ln13_fu_448_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state14_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state18_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_state22_pp0_stage1_iter5 : BOOLEAN;
    signal ap_block_state26_pp0_stage1_iter6 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal bitcast_ln13_1_fu_453_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln21_fu_483_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_reg_786 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_reg_786_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_reg_786_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_reg_786_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_reg_786_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_reg_786_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_reg_786_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal bitcast_ln21_fu_511_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln21_1_fu_516_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln13_2_fu_521_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln13_3_fu_526_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln13_15_fu_553_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln13_15_reg_831 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln13_16_fu_558_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln13_16_reg_836 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln21_1_fu_563_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln21_1_reg_841 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_266_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_857 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_reg_862 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln21_2_fu_585_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln21_3_fu_590_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln13_4_fu_595_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln13_5_fu_600_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_reg_907 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_reg_907_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_3_reg_912 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_3_reg_912_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_3_reg_912_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln21_4_fu_645_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln21_5_fu_650_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln13_6_fu_655_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln13_7_fu_660_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_4_reg_937 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_4_reg_937_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_4_reg_937_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_5_reg_942 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_5_reg_942_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_5_reg_942_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_5_reg_942_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln21_6_fu_665_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln21_7_fu_670_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_257_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_reg_957 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_6_reg_962 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_6_reg_962_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_6_reg_962_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_6_reg_962_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_7_reg_967 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_7_reg_967_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_7_reg_967_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_7_reg_967_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_7_reg_967_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_1_reg_972 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_2_reg_977 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_3_reg_982 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_4_reg_987 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_5_reg_992 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln13_fu_375_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal select_ln13_3_cast_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_fu_391_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_5_fu_406_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln13_4_cast_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal select_ln13_5_cast_fu_475_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_6_fu_495_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_7_fu_506_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln13_6_cast_fu_537_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal select_ln13_7_cast_fu_548_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_fu_566_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_8_fu_580_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln13_8_cast_fu_610_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal select_ln13_9_cast_fu_620_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_9_fu_630_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_10_fu_640_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_4_fu_675_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal o_fu_86 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_o_load : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln14_fu_411_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_fu_90 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_m_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten_fu_94 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln13_1_fu_326_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_257_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_257_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_262_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_262_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_266_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_266_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_270_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_270_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_274_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_274_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_274_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_279_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_279_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_279_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln13_fu_335_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_274_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_279_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln13_fu_380_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln21_2_fu_396_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln21_1_fu_400_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_shl_cast_fu_435_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln21_fu_432_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln13_1_fu_458_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln13_2_fu_469_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln21_fu_442_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln21_3_fu_480_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_2_fu_489_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln21_3_fu_500_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln13_3_fu_531_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln13_4_fu_542_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln21_4_fu_574_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln13_5_fu_605_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln13_6_fu_615_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln21_5_fu_625_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln21_6_fu_635_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to6 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_374 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component score_matrix_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    fadd_32ns_32ns_32_3_full_dsp_1_U1 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_257_p0,
        din1 => grp_fu_257_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_257_p2);

    fadd_32ns_32ns_32_3_full_dsp_1_U2 : component score_matrix_fadd_32ns_32ns_32_3_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_262_p0,
        din1 => grp_fu_262_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_262_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U3 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_266_p0,
        din1 => grp_fu_266_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_266_p2);

    fmul_32ns_32ns_32_2_max_dsp_1_U4 : component score_matrix_fmul_32ns_32ns_32_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_270_p0,
        din1 => grp_fu_270_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_270_p2);

    flow_control_loop_pipe_U : component score_matrix_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage3,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage3)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_374)) then
                if ((icmp_ln13_fu_320_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_94 <= add_ln13_1_fu_326_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_94 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    m_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_374)) then
                if ((icmp_ln13_fu_320_p2 = ap_const_lv1_0)) then 
                    m_fu_90 <= select_ln13_1_fu_367_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    m_fu_90 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    o_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_374)) then
                if ((icmp_ln13_fu_320_p2 = ap_const_lv1_0)) then 
                    o_fu_86 <= add_ln14_fu_411_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    o_fu_86 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_1_reg_972 <= grp_fu_257_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_2_reg_977 <= grp_fu_257_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_3_reg_982 <= grp_fu_257_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_4_reg_987 <= grp_fu_262_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_5_reg_992 <= grp_fu_262_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_713 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln21_reg_786 <= add_ln21_fu_483_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln21_reg_786_pp0_iter1_reg <= add_ln21_reg_786;
                add_ln21_reg_786_pp0_iter2_reg <= add_ln21_reg_786_pp0_iter1_reg;
                add_ln21_reg_786_pp0_iter3_reg <= add_ln21_reg_786_pp0_iter2_reg;
                add_ln21_reg_786_pp0_iter4_reg <= add_ln21_reg_786_pp0_iter3_reg;
                add_ln21_reg_786_pp0_iter5_reg <= add_ln21_reg_786_pp0_iter4_reg;
                add_ln21_reg_786_pp0_iter6_reg <= add_ln21_reg_786_pp0_iter5_reg;
                mul_6_reg_962_pp0_iter2_reg <= mul_6_reg_962;
                mul_6_reg_962_pp0_iter3_reg <= mul_6_reg_962_pp0_iter2_reg;
                mul_6_reg_962_pp0_iter4_reg <= mul_6_reg_962_pp0_iter3_reg;
                mul_7_reg_967_pp0_iter2_reg <= mul_7_reg_967;
                mul_7_reg_967_pp0_iter3_reg <= mul_7_reg_967_pp0_iter2_reg;
                mul_7_reg_967_pp0_iter4_reg <= mul_7_reg_967_pp0_iter3_reg;
                mul_7_reg_967_pp0_iter5_reg <= mul_7_reg_967_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_reg_957 <= grp_fu_257_p2;
                mul_6_reg_962 <= grp_fu_266_p2;
                mul_7_reg_967 <= grp_fu_270_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                mul_2_reg_907_pp0_iter1_reg <= mul_2_reg_907;
                mul_3_reg_912_pp0_iter1_reg <= mul_3_reg_912;
                mul_3_reg_912_pp0_iter2_reg <= mul_3_reg_912_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln13_reg_713 <= icmp_ln13_fu_320_p2;
                mul_4_reg_937_pp0_iter2_reg <= mul_4_reg_937;
                mul_4_reg_937_pp0_iter3_reg <= mul_4_reg_937_pp0_iter2_reg;
                mul_5_reg_942_pp0_iter2_reg <= mul_5_reg_942;
                mul_5_reg_942_pp0_iter3_reg <= mul_5_reg_942_pp0_iter2_reg;
                mul_5_reg_942_pp0_iter4_reg <= mul_5_reg_942_pp0_iter3_reg;
                    tmp_reg_705(4 downto 3) <= tmp_fu_310_p3(4 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln13_fu_320_p2 = ap_const_lv1_0))) then
                icmp_ln14_reg_717 <= icmp_ln14_fu_341_p2;
                select_ln13_1_reg_740 <= select_ln13_1_fu_367_p3;
                select_ln13_reg_725 <= select_ln13_fu_349_p3;
                    tmp_8_reg_732(4 downto 3) <= tmp_8_fu_357_p3(4 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_713 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_1_reg_862 <= grp_fu_270_p2;
                mul_reg_857 <= grp_fu_266_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_713 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                mul_2_reg_907 <= grp_fu_266_p2;
                mul_3_reg_912 <= grp_fu_270_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul_4_reg_937 <= grp_fu_266_p2;
                mul_5_reg_942 <= grp_fu_270_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then
                reg_284 <= grp_fu_262_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln13_reg_713 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                    select_ln13_15_reg_831(4 downto 3) <= select_ln13_15_fu_553_p3(4 downto 3);
                    select_ln13_16_reg_836(4 downto 3) <= select_ln13_16_fu_558_p3(4 downto 3);
                    zext_ln21_1_reg_841(1 downto 0) <= zext_ln21_1_fu_563_p1(1 downto 0);
            end if;
        end if;
    end process;
    tmp_reg_705(2 downto 0) <= "000";
    tmp_8_reg_732(2 downto 0) <= "000";
    select_ln13_15_reg_831(2 downto 0) <= "000";
    select_ln13_16_reg_836(2 downto 0) <= "000";
    zext_ln21_1_reg_841(4 downto 2) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to6, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to6 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln13_1_fu_326_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv4_1));
    add_ln13_fu_335_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_m_1) + unsigned(ap_const_lv2_1));
    add_ln14_fu_411_p2 <= std_logic_vector(unsigned(select_ln13_fu_349_p3) + unsigned(ap_const_lv2_1));
    add_ln21_1_fu_400_p2 <= std_logic_vector(unsigned(zext_ln21_2_fu_396_p1) + unsigned(ap_const_lv3_3));
    add_ln21_2_fu_489_p2 <= std_logic_vector(unsigned(zext_ln21_3_fu_480_p1) + unsigned(ap_const_lv4_6));
    add_ln21_3_fu_500_p2 <= std_logic_vector(unsigned(zext_ln21_3_fu_480_p1) + unsigned(ap_const_lv4_9));
    add_ln21_4_fu_574_p2 <= std_logic_vector(unsigned(zext_ln21_1_fu_563_p1) + unsigned(ap_const_lv5_F));
    add_ln21_5_fu_625_p2 <= std_logic_vector(unsigned(zext_ln21_1_reg_841) + unsigned(ap_const_lv5_12));
    add_ln21_6_fu_635_p2 <= std_logic_vector(unsigned(zext_ln21_1_reg_841) + unsigned(ap_const_lv5_15));
    add_ln21_fu_483_p2 <= std_logic_vector(unsigned(sub_ln21_fu_442_p2) + unsigned(zext_ln21_3_fu_480_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage2_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage3_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage2_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage3_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage1_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage2_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage3_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage1_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage2_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage3_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage1_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage2_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage3_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage3_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_374_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_374 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, icmp_ln13_reg_713)
    begin
        if (((icmp_ln13_reg_713 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to6 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to6 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage3;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_94)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_94;
        end if; 
    end process;


    ap_sig_allocacmp_m_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, m_fu_90)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_m_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_m_1 <= m_fu_90;
        end if; 
    end process;


    ap_sig_allocacmp_o_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, o_fu_86, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_o_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_o_load <= o_fu_86;
        end if; 
    end process;

    bitcast_ln13_1_fu_453_p1 <= queries_q0;
    bitcast_ln13_2_fu_521_p1 <= queries_q1;
    bitcast_ln13_3_fu_526_p1 <= queries_q0;
    bitcast_ln13_4_fu_595_p1 <= queries_q1;
    bitcast_ln13_5_fu_600_p1 <= queries_q0;
    bitcast_ln13_6_fu_655_p1 <= queries_q1;
    bitcast_ln13_7_fu_660_p1 <= queries_q0;
    bitcast_ln13_fu_448_p1 <= queries_q1;
    bitcast_ln21_1_fu_516_p1 <= keys_t_q0;
    bitcast_ln21_2_fu_585_p1 <= keys_t_q1;
    bitcast_ln21_3_fu_590_p1 <= keys_t_q0;
    bitcast_ln21_4_fu_645_p1 <= keys_t_q1;
    bitcast_ln21_5_fu_650_p1 <= keys_t_q0;
    bitcast_ln21_6_fu_665_p1 <= keys_t_q1;
    bitcast_ln21_7_fu_670_p1 <= keys_t_q0;
    bitcast_ln21_fu_511_p1 <= keys_t_q1;

    grp_fu_257_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, mul_reg_857, add_reg_957, add_1_reg_972, add_2_reg_977, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_257_p0 <= add_2_reg_977;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_257_p0 <= add_1_reg_972;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_257_p0 <= add_reg_957;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_257_p0 <= mul_reg_857;
        else 
            grp_fu_257_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_257_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, mul_1_reg_862, mul_2_reg_907_pp0_iter1_reg, mul_3_reg_912_pp0_iter2_reg, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_257_p1 <= mul_3_reg_912_pp0_iter2_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_257_p1 <= mul_2_reg_907_pp0_iter1_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_257_p1 <= mul_1_reg_862;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_257_p1 <= ap_const_lv32_0;
        else 
            grp_fu_257_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_262_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage3, reg_284, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, add_3_reg_982, add_4_reg_987, add_5_reg_992, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_262_p0 <= reg_284;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_262_p0 <= add_5_reg_992;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_262_p0 <= add_4_reg_987;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_262_p0 <= add_3_reg_982;
        else 
            grp_fu_262_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_262_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, mul_4_reg_937_pp0_iter3_reg, mul_5_reg_942_pp0_iter4_reg, mul_6_reg_962_pp0_iter4_reg, mul_7_reg_967_pp0_iter5_reg, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_262_p1 <= mul_7_reg_967_pp0_iter5_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_262_p1 <= mul_6_reg_962_pp0_iter4_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_262_p1 <= mul_5_reg_942_pp0_iter4_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_262_p1 <= mul_4_reg_937_pp0_iter3_reg;
        else 
            grp_fu_262_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_266_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, bitcast_ln13_fu_448_p1, ap_CS_fsm_pp0_stage1, bitcast_ln13_2_fu_521_p1, bitcast_ln13_4_fu_595_p1, bitcast_ln13_6_fu_655_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_266_p0 <= bitcast_ln13_6_fu_655_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_266_p0 <= bitcast_ln13_4_fu_595_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_266_p0 <= bitcast_ln13_2_fu_521_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_266_p0 <= bitcast_ln13_fu_448_p1;
        else 
            grp_fu_266_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_266_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, bitcast_ln21_fu_511_p1, bitcast_ln21_2_fu_585_p1, bitcast_ln21_4_fu_645_p1, bitcast_ln21_6_fu_665_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_266_p1 <= bitcast_ln21_6_fu_665_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_266_p1 <= bitcast_ln21_4_fu_645_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_266_p1 <= bitcast_ln21_2_fu_585_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_266_p1 <= bitcast_ln21_fu_511_p1;
        else 
            grp_fu_266_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_270_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, bitcast_ln13_1_fu_453_p1, bitcast_ln13_3_fu_526_p1, bitcast_ln13_5_fu_600_p1, bitcast_ln13_7_fu_660_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_270_p0 <= bitcast_ln13_7_fu_660_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_270_p0 <= bitcast_ln13_5_fu_600_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_270_p0 <= bitcast_ln13_3_fu_526_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_270_p0 <= bitcast_ln13_1_fu_453_p1;
        else 
            grp_fu_270_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_270_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, bitcast_ln21_1_fu_516_p1, bitcast_ln21_3_fu_590_p1, bitcast_ln21_5_fu_650_p1, bitcast_ln21_7_fu_670_p1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_270_p1 <= bitcast_ln21_7_fu_670_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_270_p1 <= bitcast_ln21_5_fu_650_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_270_p1 <= bitcast_ln21_3_fu_590_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_270_p1 <= bitcast_ln21_1_fu_516_p1;
        else 
            grp_fu_270_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_274_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, icmp_ln14_fu_341_p2, icmp_ln14_reg_717, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_274_p0 <= icmp_ln14_reg_717;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_274_p0 <= icmp_ln14_fu_341_p2;
        else 
            grp_fu_274_p0 <= "X";
        end if; 
    end process;


    grp_fu_274_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, tmp_8_fu_357_p3, tmp_8_reg_732, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_274_p1 <= tmp_8_reg_732;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_274_p1 <= tmp_8_fu_357_p3;
        else 
            grp_fu_274_p1 <= "XXXXX";
        end if; 
    end process;


    grp_fu_274_p2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, tmp_fu_310_p3, tmp_reg_705, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_274_p2 <= tmp_reg_705;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_274_p2 <= tmp_fu_310_p3;
        else 
            grp_fu_274_p2 <= "XXXXX";
        end if; 
    end process;

    grp_fu_274_p3 <= 
        grp_fu_274_p1 when (grp_fu_274_p0(0) = '1') else 
        grp_fu_274_p2;

    grp_fu_279_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, icmp_ln14_fu_341_p2, icmp_ln14_reg_717, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_279_p0 <= icmp_ln14_reg_717;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_279_p0 <= icmp_ln14_fu_341_p2;
        else 
            grp_fu_279_p0 <= "X";
        end if; 
    end process;


    grp_fu_279_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, tmp_8_fu_357_p3, tmp_8_reg_732, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_279_p1 <= tmp_8_reg_732;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_279_p1 <= tmp_8_fu_357_p3;
        else 
            grp_fu_279_p1 <= "XXXXX";
        end if; 
    end process;


    grp_fu_279_p2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, tmp_fu_310_p3, tmp_reg_705, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_279_p2 <= tmp_reg_705;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_279_p2 <= tmp_fu_310_p3;
        else 
            grp_fu_279_p2 <= "XXXXX";
        end if; 
    end process;

    grp_fu_279_p3 <= 
        grp_fu_279_p1 when (grp_fu_279_p0(0) = '1') else 
        grp_fu_279_p2;
    icmp_ln13_fu_320_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv4_9) else "0";
    icmp_ln14_fu_341_p2 <= "1" when (ap_sig_allocacmp_o_load = ap_const_lv2_3) else "0";

    keys_t_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln21_5_fu_406_p1, ap_block_pp0_stage1, zext_ln21_7_fu_506_p1, ap_block_pp0_stage2, zext_ln21_8_fu_580_p1, ap_block_pp0_stage3, zext_ln21_10_fu_640_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                keys_t_address0 <= zext_ln21_10_fu_640_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                keys_t_address0 <= zext_ln21_8_fu_580_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                keys_t_address0 <= zext_ln21_7_fu_506_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                keys_t_address0 <= zext_ln21_5_fu_406_p1(5 - 1 downto 0);
            else 
                keys_t_address0 <= "XXXXX";
            end if;
        else 
            keys_t_address0 <= "XXXXX";
        end if; 
    end process;


    keys_t_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln14_fu_391_p1, ap_block_pp0_stage1, zext_ln21_6_fu_495_p1, ap_block_pp0_stage2, tmp_s_fu_566_p3, ap_block_pp0_stage3, zext_ln21_9_fu_630_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                keys_t_address1 <= zext_ln21_9_fu_630_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                keys_t_address1 <= tmp_s_fu_566_p3(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                keys_t_address1 <= zext_ln21_6_fu_495_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                keys_t_address1 <= zext_ln14_fu_391_p1(5 - 1 downto 0);
            else 
                keys_t_address1 <= "XXXXX";
            end if;
        else 
            keys_t_address1 <= "XXXXX";
        end if; 
    end process;


    keys_t_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            keys_t_ce0 <= ap_const_logic_1;
        else 
            keys_t_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    keys_t_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            keys_t_ce1 <= ap_const_logic_1;
        else 
            keys_t_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln13_1_fu_458_p2 <= (grp_fu_274_p3 or ap_const_lv5_2);
    or_ln13_2_fu_469_p2 <= (grp_fu_279_p3 or ap_const_lv5_3);
    or_ln13_3_fu_531_p2 <= (grp_fu_274_p3 or ap_const_lv5_4);
    or_ln13_4_fu_542_p2 <= (grp_fu_279_p3 or ap_const_lv5_5);
    or_ln13_5_fu_605_p2 <= (select_ln13_15_reg_831 or ap_const_lv5_6);
    or_ln13_6_fu_615_p2 <= (select_ln13_16_reg_836 or ap_const_lv5_7);
    or_ln13_fu_380_p2 <= (grp_fu_279_p3 or ap_const_lv5_1);
    p_shl_cast_fu_435_p3 <= (select_ln13_1_reg_740 & ap_const_lv2_0);

    queries_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, select_ln13_3_cast_fu_386_p1, ap_block_pp0_stage1, select_ln13_5_cast_fu_475_p1, ap_block_pp0_stage2, select_ln13_7_cast_fu_548_p1, ap_block_pp0_stage3, select_ln13_9_cast_fu_620_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                queries_address0 <= select_ln13_9_cast_fu_620_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                queries_address0 <= select_ln13_7_cast_fu_548_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                queries_address0 <= select_ln13_5_cast_fu_475_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                queries_address0 <= select_ln13_3_cast_fu_386_p1(5 - 1 downto 0);
            else 
                queries_address0 <= "XXXXX";
            end if;
        else 
            queries_address0 <= "XXXXX";
        end if; 
    end process;


    queries_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, zext_ln13_fu_375_p1, ap_block_pp0_stage0, select_ln13_4_cast_fu_464_p1, ap_block_pp0_stage1, select_ln13_6_cast_fu_537_p1, ap_block_pp0_stage2, select_ln13_8_cast_fu_610_p1, ap_block_pp0_stage3)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                queries_address1 <= select_ln13_8_cast_fu_610_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                queries_address1 <= select_ln13_6_cast_fu_537_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                queries_address1 <= select_ln13_4_cast_fu_464_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                queries_address1 <= zext_ln13_fu_375_p1(5 - 1 downto 0);
            else 
                queries_address1 <= "XXXXX";
            end if;
        else 
            queries_address1 <= "XXXXX";
        end if; 
    end process;


    queries_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            queries_ce0 <= ap_const_logic_1;
        else 
            queries_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    queries_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            queries_ce1 <= ap_const_logic_1;
        else 
            queries_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    score_m_address0 <= zext_ln21_4_fu_675_p1(4 - 1 downto 0);

    score_m_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            score_m_ce0 <= ap_const_logic_1;
        else 
            score_m_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    score_m_d0 <= reg_284;

    score_m_we0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            score_m_we0 <= ap_const_logic_1;
        else 
            score_m_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln13_15_fu_553_p3 <= 
        tmp_8_reg_732 when (icmp_ln14_reg_717(0) = '1') else 
        tmp_reg_705;
    select_ln13_16_fu_558_p3 <= 
        tmp_8_reg_732 when (icmp_ln14_reg_717(0) = '1') else 
        tmp_reg_705;
    select_ln13_1_fu_367_p3 <= 
        add_ln13_fu_335_p2 when (icmp_ln14_fu_341_p2(0) = '1') else 
        ap_sig_allocacmp_m_1;
    select_ln13_3_cast_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_fu_380_p2),64));
    select_ln13_4_cast_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_1_fu_458_p2),64));
    select_ln13_5_cast_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_2_fu_469_p2),64));
    select_ln13_6_cast_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_3_fu_531_p2),64));
    select_ln13_7_cast_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_4_fu_542_p2),64));
    select_ln13_8_cast_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_5_fu_605_p2),64));
    select_ln13_9_cast_fu_620_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_6_fu_615_p2),64));
    select_ln13_fu_349_p3 <= 
        ap_const_lv2_0 when (icmp_ln14_fu_341_p2(0) = '1') else 
        ap_sig_allocacmp_o_load;
    sub_ln21_fu_442_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_435_p3) - unsigned(zext_ln21_fu_432_p1));
    tmp_8_fu_357_p3 <= (add_ln13_fu_335_p2 & ap_const_lv3_0);
    tmp_fu_310_p3 <= (ap_sig_allocacmp_m_1 & ap_const_lv3_0);
    tmp_s_fu_566_p3 <= (ap_const_lv62_3 & select_ln13_reg_725);
    zext_ln13_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_274_p3),64));
    zext_ln14_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln13_fu_349_p3),64));
    zext_ln21_10_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_6_fu_635_p2),64));
    zext_ln21_1_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln13_reg_725),5));
    zext_ln21_2_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln13_fu_349_p3),3));
    zext_ln21_3_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln13_reg_725),4));
    zext_ln21_4_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_reg_786_pp0_iter6_reg),64));
    zext_ln21_5_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_1_fu_400_p2),64));
    zext_ln21_6_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_2_fu_489_p2),64));
    zext_ln21_7_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_3_fu_500_p2),64));
    zext_ln21_8_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_4_fu_574_p2),64));
    zext_ln21_9_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_5_fu_625_p2),64));
    zext_ln21_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln13_1_reg_740),4));
end behav;
